### ISSUE TITLE
点击插件图标无反应

### ISSUE THREAD

**Issue by hyjwonder** [OverflowCat/logseq-simpread#3]
问题：在Mac上，从Logseq插件市场安装SimpRead插件后，最初点击SimpRead插件会显示一个稍后读窗格。后来，不知怎么着，再点击这个图标就无反应了。
重装过Logseq、重装插件、重启同步助手，都无效。
在浏览器上输入：http://localhost:7026/unread/?embed=logseq 显示正常。
还请开发者帮忙诊断是什么问题。谢谢！

![telegram-cloud-photo-size-5-6271525011445625013-y](https://user-images.githubusercontent.com/77609410/181206462-fc8379d4-e297-46ec-b7a4-03331740c8a4.jpg)

![telegram-cloud-photo-size-5-6271525011445625018-y](https://user-images.githubusercontent.com/77609410/181206593-48834847-a536-4ea5-b528-c1a3c119b9b6.jpg)

**Comment by OverflowCat** [comment]
Solved in [t.me/simpreadgroup/61574](https://t.me/simpreadgroup/61574).

**Comment by mtuwei** [comment]
> Solved in [t.me/simpreadgroup/61574](https://t.me/simpreadgroup/61574).

您好！Logseq更新至【0.8.2 Wiin】版本后，出现了同样的问题。清空『custom.css』问题依然存在，麻烦您看下如何解决，谢谢！

**Comment by OverflowCat** [comment]
![image](https://user-images.githubusercontent.com/20166026/187185942-0ea7d504-d6a0-45b5-94b6-9b8eddedd237.png)
@mtuwei 无法复现
请看一下控制台（<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>）有无报错
![image](https://user-images.githubusercontent.com/20166026/187186425-ee341c7a-8048-4f2e-ad90-995f1e6baedf.png)

**Comment by mtuwei** [comment]
> ![image](https://user-images.githubusercontent.com/20166026/187185942-0ea7d504-d6a0-45b5-94b6-9b8eddedd237.png) @mtuwei 无法复现 请看一下控制台（Ctrl+Shift+I）有无报错 ![image](https://user-images.githubusercontent.com/20166026/187186425-ee341c7a-8048-4f2e-ad90-995f1e6baedf.png)

您好，我这边的报错信息如下：
![image](https://user-images.githubusercontent.com/32591958/187224908-7078a07e-6708-4249-9393-085373d0cf00.png)

**Comment by OverflowCat** [comment]
@mtuwei 在浏览器访问 http://localhost:7026/unread/?embed=logseq 能正常显示吗？看起来是同步助手的服务的问题。

如果浏览器能正常显示列表，那么请在控制台最下方输入
```js
document.querySelector("iframe.simpread-iframe")['src'] = "https://baidu.com";
```
看看能否加载出百度首页。

**Comment by mtuwei** [comment]
> http://localhost:7026/unread/?embed=logseq



> @mtuwei 在浏览器访问 http://localhost:7026/unread/?embed=logseq 能正常显示吗？看起来是同步助手的服务的问题。
> 
> 如果浏览器能正常显示列表，那么请在控制台最下方输入
> 
> ```js
> document.querySelector("iframe.simpread-iframe")['src'] = "https://baidu.com";
> ```
> 
> 看看能否加载出百度首页。 ![image](https://user-images.githubusercontent.com/20166026/187228376-96590b0b-0bc6-4f0f-b545-0f9c7180e1e7.png)

确实是『同步助手』服务的问题，提示同样的错误。重启『同步助手』后，能正常显示了，谢谢！
![image](https://user-images.githubusercontent.com/32591958/187229718-b74c4cf7-b07c-480f-83c1-b93da3284432.png)

**Comment by OverflowCat** [comment]
目前这个插件只是做了个劫持链接在侧栏显示的工作，不会也无法注入简悦提供的这个简单版稍后读列表，如果有问题可以直接浏览器访问链接，可以参考之前手动插入 `iframe` 代码的教程

**Comment by dofine** [comment]
您好，请问在升级到 Logseq 0.8.11 之后我也遇到这个问题。按照前述的排查方案
<img width="536" alt="CleanShot 2022-11-19 at 21 40 15@2x" src="https://user-images.githubusercontent.com/440101/202853520-a94cf448-5764-4c9c-b321-fb555a7a5b46.png">

加载baidu时报错：
<img width="534" alt="CleanShot 2022-11-19 at 21 39 58@2x" src="https://user-images.githubusercontent.com/440101/202853504-d93fdffa-8697-458f-a16c-d51ef0376c55.png">

**Comment by OverflowCat** [comment]
@dofine 

> 您好，请问在升级到 Logseq 0.8.11 之后我也遇到这个问题。按照前述的排查方案 [图片]
> 加载baidu时报错： [图片]

请告知一下系统环境，我这边也是 0.8.11，目前阅读列表页面和百度都正常，百度虽然有 cross-origin 报错但仍可以正常加载。

![image](https://user-images.githubusercontent.com/20166026/202856522-068107f4-2bb0-40cc-9768-83f7d30c142d.png)

**Comment by dofine** [comment]
您好，不好意思是我忘记中间又修改过一次 custom.css 了。清空 custom.css 之后正常 😄

**Comment by OverflowCat** [comment]
@dofine 按理说 CSS 应该不会造成什么影响，你可以把你的 CSS 发出来我看一下有哪边可能会冲突
