### ISSUE TITLE
Linux版本无法导出 markdown格式文件

### ISSUE THREAD

**Issue by xtz136** [OverflowCat/logseq-simpread#4]
你好，我按教程安装后，尝试在logseq里面标注一篇文章，并没有成功导出 markdown 格式文件：

1. 使用的系统是 Deepin，版本是 20.6
2. 同步助手版本是 1.1.2
3. 进入阅读模式后，能成功导出 html 格式文件
4. 在 logseq 里面标注后，导出目录多了一个 「文章标题].org 的空文件，但没有 markdown 格式文件
5. 在 logseq 里面调试，接口 http://localhost:7027/unread 报错了，接口没有返回任何内容
6. 在同步助手里面打开日志，再次标注，接口报错了，但是日志 simpred_sync.log 没有任何内容
7. 相同步骤在 windows 10 可以成功导出 markdown 格式文件

**Comment by lyserenity** [comment]
我先帮回部分好了：

因为你导出的文件是 ``org`` ，加上是空文件，也没有提到相关讯息，所以我怀疑是插件的设置没设对或忘记了，也许你可以确认一下。
如果都设置了，再来考虑下有没有其他的可能....

<img width="500" alt="image" src="https://user-images.githubusercontent.com/32646062/201017945-092e8c03-86ed-492c-bba0-2c2724a9cf2e.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/32646062/201016868-629612ac-0f27-4864-8855-4a77b0ce63b6.png">

另一个是 ``http://localhost:7027/unread `` 没有返回的问题，也许再核对一下同步助手的设置，或重启试试？

**Comment by xtz136** [comment]
> 我先帮回部分好了：
> 
> 因为你导出的文件是 `org` ，加上是空文件，也没有提到相关讯息，所以我怀疑是插件的设置没设对或忘记了，也许你可以确认一下。 如果都设置了，再来考虑下有没有其他的可能....
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/32646062/201017945-092e8c03-86ed-492c-bba0-2c2724a9cf2e.png">
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/32646062/201016868-629612ac-0f27-4864-8855-4a77b0ce63b6.png">
> 
> 另一个是 `http://localhost:7027/unread ` 没有返回的问题，也许再核对一下同步助手的设置，或重启试试？

非常感谢，确实是我没有设置 logseq 里的简悦插件。目前可以导出 markdown 格式文件。
至于 http://localhost:7027/unread 接口问题，好像并不影响我，除了不提示保存成功，没发现有其他问题。
