### ISSUE TITLE
微信公众号 图片无法加载

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [OverflowCat/logseq-simpread#7]
![image](https://user-images.githubusercontent.com/39046975/236715038-e8340099-c04f-4996-a536-3c030a3f720d.png)

**Comment by OverflowCat** [comment]
微信有图片防盗链，目前存不了 assets，用 base64 的话文件又会很大。我这边没法单独做到。可以去简悦那边提个 issue。
